insert into SCHEDULE_TIME(START_TIME, END_TIME) values ('12:00', '14:00')
insert into SCHEDULE_TIME(START_TIME, END_TIME) values ('12:00', '15:00')
insert into SCHEDULE_TIME(START_TIME, END_TIME) values ('12:00', '15:00')
insert into SCHEDULE_TIME(START_TIME, END_TIME) values ('12:00', '14:00')
insert into SCHEDULE_TIME(START_TIME, END_TIME) values ('13:00', '16:00')
insert into SCHEDULE_TIME(START_TIME, END_TIME) values ('13:00', '16:00')
insert into SCHEDULE_TIME(START_TIME, END_TIME) values ('13:00', '16:00')
insert into SCHEDULE_TIME(START_TIME, END_TIME) values ('13:00', '16:00')
insert into EMPLOYEE(FIRST_NAME, LAST_NAME, SCHEDULE_TIME_ID) values ('ivan', 'ramanau','1')
insert into EMPLOYEE(FIRST_NAME, LAST_NAME, SCHEDULE_TIME_ID) values ('egor', 'grishenkov','2')
insert into EMPLOYEE(FIRST_NAME, LAST_NAME, SCHEDULE_TIME_ID) values ('valentin', 'kaptur','3')
insert into EMPLOYEE(FIRST_NAME, LAST_NAME, SCHEDULE_TIME_ID) values ('ivan', 'kulagin','4')
insert into EMPLOYEE(FIRST_NAME, LAST_NAME, SCHEDULE_TIME_ID) values ('alexey', 'zabkov', '5')
insert into EMPLOYEE(FIRST_NAME, LAST_NAME, SCHEDULE_TIME_ID) values ('anton', 'goffman', '6')
insert into EMPLOYEE(FIRST_NAME, LAST_NAME, SCHEDULE_TIME_ID) values ('igor', 'rodoslavovich', '7')
insert into EMPLOYEE(FIRST_NAME, LAST_NAME, SCHEDULE_TIME_ID) values ('georgiy', 'dybov', '8')